In [8]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[8,9,10]])

print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
print(A[0])

안


In [10]:
print("안녕하세요 \n 반갑습니다.")
print("이번 시험의 성적으로 %d점을 맞았습니다."%3)
print("이번 시험의 성적으로 %0.3f점을 맞았습니다."%3.33333)
print(("이번 시험의 성적으로 {}점을 맞았습니다.").format(100))
print(("이번 시험에서 수학은 {}점 영어는 {}점 국어는 {}점을 맞았습니다.").format(100, 100, 100))
print(("{:.2f},{:.3f}").format(3.1415, 3.1414))

안녕하세요 
 반갑습니다.
이번 시험의 성적으로 3점을 맞았습니다.
이번 시험의 성적으로 3.333점을 맞았습니다.
이번 시험의 성적으로 100점을 맞았습니다.
이번 시험에서 수학은 100점 영어는 100점 국어는 100점을 맞았습니다.
3.14,3.141


In [15]:
print(A)
b = A.replace("안녕하세요", "")
print(b)

안녕하세요 지금은 데이터 전처리 수업 시간입니다.
 지금은 데이터 전처리 수업 시간입니다.


In [16]:
a = [10, 20, 30, 40, 50, 60, 70, 80, 90]

a[0] + a[5]

70

In [40]:
a = ["독고영재, 50", "김철수, 30"]
b = ["김철수, 20", "김영희, 25"]
print(a[0][:a[0].index(",")], ", ", b[0][:b[0].index(",")])

독고영재 ,  김철수


In [44]:
a = ["hi", 10, "80", "Kim", 50, 50.6]

a.pop(1) # index 1에 있는 값 제거
print('값 제거: ', a)

a.append("4/13") # 값 맨 뒤에 추가
print('값 추가: ', a)

값 제거:  ['hi', '80', 'Kim', 50, 50.6]
값 추가:  ['hi', '80', 'Kim', 50, 50.6, '4/13']


In [51]:
b = np.array([1,2,3,4])
b = np.append(b, [4,5])

# index 1에 [7, 8] 추가
b = np.insert(b, 1, [7, 8])

print('배열 추가:', b)

# index 1, 3 에 있는 값 제거
b = np.delete(b, [1, 3])
print('배열 인덱스 제거:', b)

print(b[b<=4])
print(b[b!=4])

배열 추가: [1 7 8 2 3 4 4 5]
배열 인덱스 제거: [1 8 3 4 4 5]
[1 3 4 4]
[1 8 3 5]


In [55]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

# Data Vertical Merge
merge_verarr = np.vstack((arr1, arr2))
print('Vertical Merge:', merge_verarr)

# Data Horizontal Merge
merge_harr = np.hstack((arr1, arr2))
print('Horizontal Merge:', merge_harr)

Vertical Merge: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Merge: [[1 2 5 6]
 [3 4 7 8]]


In [68]:
# Dictonary

a = {1: "Kim", 20: "Park"}
print('a[1]=', a[1], '\na[20]=', a[20], '\na.get(1)=', a.get(1), '\na.get(3)=', a.get(3))

# Add Dict
a["2-a"] = "Pak"
print('Add Dict:',a)

# Delete Dict
del a[20]
print('Delete Dict:',a)

a[1]= Kim 
a[20]= Park 
a.get(1)= Kim 
a.get(3)= None
Add Dict: {1: 'Kim', 20: 'Park', '2-a': 'Pak'}
Delete Dict: {1: 'Kim', '2-a': 'Pak'}
