In [13]:
alist = [1, 5, 7, 8, 10, "안녕", "a"]
alist

[1, 5, 7, 8, 10, '안녕', 'a']

In [8]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 3, 5, 6])
print(arr1+arr2)

[ 3  5  8 10]


In [9]:
arr3 = np.array([[1,2,3,4,5,6],[20,19,18,17,16,15]])
print(arr3)

[[ 1  2  3  4  5  6]
 [20 19 18 17 16 15]]


In [12]:
print("-"*15)
print("데이터전처리 수업\n끝")
print("="*15)

---------------
데이터전처리 수업
끝
